### ISSUE TITLE
Failed to intall / register the plugin

### ISSUE THREAD

**Issue by JeroenDM** [JeroenDM/moveit_opw_kinematics_plugin#2]
When I configure a robot to use the plugin and launch the default demo.launch I get the error:

```
ros.moveit_ros_planning: The kinematics plugin (manipulator) failed to load. Error:
According to the loaded plugin descriptions the class moveit_opw_kinematics_plugin/MoveItOPWKinematicsPlugin with base class type
kinematics::KinematicsBase does not exist.
Declared types are  cached_ik_kinematics_plugin/CachedKDLKinematicsPlugin
cached_ik_kinematics_plugin/CachedSrvKinematicsPlugin kdl_kinematics_plugin/KDLKinematicsPlugin
lma_kinematics_plugin/LMAKinematicsPlugin srv_kinematics_plugin/SrvKinematicsPlugin
trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin ur_kinematics/UR10KinematicsPlugin
ur_kinematics/UR3KinematicsPlugin ur_kinematics/UR5KinematicsPlugin
ros.moveit_ros_planning: Kinematics solver could not be instantiated for joint group manipulator.
```

The kinematics.yaml file looks like this:
```yaml
manipulator:
  kinematics_solver: moveit_opw_kinematics_plugin/MoveItOPWKinematicsPlugin
  kinematics_solver_geometric_parameters:
    a1:  0.025
    a2: -0.035
    b:   0.000
    c1:  0.400
    c2:  0.315
    c3:  0.365
    c4:  0.080
  kinematics_solver_joint_offsets: [0.0, -1.57079632679, 0, 0, 0, 0]
```

I'm using the [universal robot kinematics plugin](https://github.com/ros-industrial/universal_robot/tree/kinetic-devel/ur_kinematics) as a reference for the configuration. This resulted in several things:

- A [description file](https://github.com/JeroenDM/moveit_opw_kinematics_plugin/blob/325b509c080ddacbb2db64154ae30ce958ad7863/moveit_opw_kinematics_plugin_description.xml).
- A call to the [CLASS_LOADER_REGISTER_CLASS](https://github.com/JeroenDM/moveit_opw_kinematics_plugin/blob/master/src/moveit_opw_kinematics_plugin.cpp#L22) macro in the source file.
- Several [settings](https://github.com/JeroenDM/moveit_opw_kinematics_plugin/blob/325b509c080ddacbb2db64154ae30ce958ad7863/CMakeLists.txt#L97) in the CMakeLists.txt.

I looked around in the MoveIt API and in the KDL en srv plugins, but I've not found the problem yet.
