### ISSUE TITLE
Extract parameters from robot description instead of reading them from kinematics.yaml

### ISSUE THREAD

**Issue by JeroenDM** [JeroenDM/moveit_opw_kinematics_plugin#3]
In the current version, all input parameters needed for the `opw_kinematics` solver are specified in the `kinematics.yaml` like this;

```yaml
manipulator:
  kinematics_solver: moveit_opw_kinematics_plugin/MoveItOPWKinematicsPlugin
  kinematics_solver_geometric_parameters:
    a1:  0.025
    a2: -0.035
    b:   0.000
    c1:  0.400
    c2:  0.315
    c3:  0.365
    c4:  0.080
  kinematics_solver_joint_offsets: [0.0, -1.57079632679, 0, 0, 0, 0]
```
And the plugin [reads the parameters](https://github.com/JeroenDM/moveit_opw_kinematics_plugin/blob/325b509c080ddacbb2db64154ae30ce958ad7863/src/moveit_opw_kinematics_plugin.cpp#L140) during initialization.
I should be straightforward to extract these from the robot description using the RobotModel API from MoveIt!.

But then there should also be a check whether the robot is compatible.
